### ISSUE TITLE
Audio stopped

### ISSUE THREAD

**Issue by CFNR** [openbroadcaster/obplayer#14]
Any reason why the station's audio stopped at 2 am and several test alerts in a row played after that spaced out by several minutes of silence?

**Comment by geoplanet** [comment]
The Player maintains log files that are helpful when debugging connection issues. Log files are identified by date, and  logs are stored in ~/.openbroadcaster/logs. When reporting issues, please include an excerpt from the log files for that period, so that the possible causes may be more easily identified and addressed.

**Comment by CFNR** [comment]
We (a tech from OB and myself) attempted to do that but apparently the log files are only kept for a set amount of time so there were none available by the time follow up was done.  It would appear that there's no solution so perhaps the thread should be closed.
