### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by iesfausti** [openbroadcaster/obplayer#17]
Hi
First of all thanks for the code, good job.
I found a minor bug in media playing  with accents in OBPlayer
Line 74 in obplayer/fallback/fallback_player.py
shoud be 
 for (dirname, dirnames, filenames) in os.walk( unicode(obplayer.Config.setting('fallback_media'))):
                                                                           -----------
instead of 
 for (dirname, dirnames, filenames) in os.walk( obplayer.Config.setting('fallback_media')):

**Comment by transistorfet** [comment]
Thanks for the bug report.  I've patched this issue and pushed it to the testing branch.  I'll leave it to @geoplanet to push the fix out to production.

This fix will allow subdirectories and filenames in the fallback media directory to contain unicode characters, but it will still not support unicode in the fallback media directory setting in the dashboard.  A much better solution to the unicode problem is to run the player using Python3.  Python3 supports unicode natively whereas Python2 does not.  In order to get it to work, the python3 versions of all the same dependency packages must be installed and the obplayer_check shell script must be modified to use the 'python3' command line program instead of 'python'.  If you find any bugs while running the player in Python3, please let us know.

@geoplanet : we should really see about migrating the install base to Python3 as soon as possible.

**Comment by geoplanet** [comment]
Changes merged testing->master->production 

Migrating install base along with the newest ubuntu &/or debian
distibution is a priority. 

J 

On 2016-07-18 15:50, transistor fet wrote: 

> Thanks for the bug report. I've patched this issue and pushed it to the testing branch. I'll leave it to @geoplanet [1] to push the fix out to production. 
> 
> This fix will allow subdirectories and filenames in the fallback media directory to contain unicode characters, but it will still not support unicode in the fallback media directory setting in the dashboard. A much better solution to the unicode problem is to run the player using Python3. Python3 supports unicode natively whereas Python2 does not. In order to get it to work, the python3 versions of all the same dependency packages must be installed and the obplayer_check shell script must be modified to use the 'python3' command line program instead of 'python'. If you find any bugs while running the player in Python3, please let us know. 
> 
> @geoplanet [1] : we should really see about migrating the install base to Python3 as soon as possible. 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

  

Links:
------
[1] https://github.com/geoplanet
[2]
https://github.com/openbroadcaster/obplayer/issues/17#issuecomment-233482583
[3]
