### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by awdsystems** [openbroadcaster/obplayer#24]
Would it be possible to have an option for shoutcast as streaming server?

**Comment by transistorfet** [comment]
OpenBroadcaster currently supports icecast2 and shoutcast through the HTTP protocol.  Are you having trouble getting this to work with an existing shoutcast server?  There is an option in gstreamer to use the Icy Protocol instead of HTTP if needed, which could be made into an option on the dashboard.
