### ISSUE TITLE
Output Bitrate Increase & Autostart 

### ISSUE THREAD

**Issue by ralphotowo** [openbroadcaster/obplayer#27]
I have obplayer installed on an Ubuntu 16.04 LTS server. Currently, I start obplayer by changing to the directory where it's installed and running `bash obplayer_loop -d -r`. I would like to automate its startup and was wondering if there's a standard way of doing, or if you have any init scripts to share? 

Secondly, On the streaming tab, the Icecast Output bitrate is currently set to "Variable", is it possible to increase this past the current maximum setting of 320kbps?

**Comment by transistorfet** [comment]
You'll have to ask @radiorob about scripts.  Our standard way of doing it is to set up obplayer as a systemd user service, and to enable user lingering in systemd so that the user's session is started without the user logging in.  I think this is only needed because of pulseaudio and its need for dbus, which requires a user sessions if I'm not mistaken.  If you aren't using pulseaudio, you should be able to get away with a simple rc script that runs the command you mentioned.

The bitrate only applies to the audio-only output mode, which encodes the audio into mp3, which has a maximum bitrate of 320kbits, so really that option should be hidden when video mode is selected.  For the video mode, it encodes the audio into ogg and the video into theora, and it uses the default variable bitrate, as determined by gstreamer.

**Comment by radiorob** [comment]
Fixed. Can set custom encoding rates on independent icecast streams.

Deb package automates the installation of player runs under a system service with the service name of obplayer. Commands to restart, stop, and start the service.

sudo service obplayer start
sudo service obplayer stop
sudo service obplayer restart
